import { Keypair, PublicKey } from "@solana/web3.js";

// ============================================================
// Localnet Keypairs for zynk-protocol-solana-programs
// Generated by `solana-keygen new`
// ============================================================

// Program IDs
export const ZYNK_CORE_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    211, 218, 70, 156, 28, 238, 167, 241, 71, 120, 219, 175, 56, 141, 158, 67,
    223, 237, 149, 162, 166, 197, 147, 76, 191, 52, 133, 234, 31, 178, 230,
    153, 196, 180, 94, 29, 34, 146, 193, 56, 23, 119, 37, 192, 57, 27, 111,
    237, 148, 78, 69, 42, 199, 254, 22, 147, 94, 108, 213, 100, 27, 80, 193,
    218,
  ])
);
export const ZYNK_CORE_PROGRAM_ID = ZYNK_CORE_KEYPAIR.publicKey;

export const ZYNK_ORBIT_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    233, 91, 169, 33, 39, 195, 100, 13, 230, 127, 73, 4, 13, 60, 200, 137,
    137, 204, 84, 113, 225, 28, 100, 190, 198, 110, 76, 15, 194, 174, 126,
    241, 240, 38, 164, 176, 204, 230, 235, 145, 79, 78, 64, 250, 45, 16, 128,
    122, 26, 24, 29, 178, 56, 40, 132, 30, 3, 225, 249, 58, 120, 224, 15, 156,
  ])
);
export const ZYNK_ORBIT_PROGRAM_ID = ZYNK_ORBIT_KEYPAIR.publicKey;

// Orbit constants
export const ZOV_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    78, 50, 48, 23, 23, 174, 251, 222, 105, 223, 18, 208, 18, 216, 63, 163,
    196, 62, 165, 21, 167, 72, 246, 14, 24, 150, 26, 22, 247, 199, 121, 38,
    208, 250, 115, 48, 166, 148, 240, 200, 206, 131, 200, 90, 44, 160, 173,
    112, 223, 180, 253, 206, 146, 97, 46, 43, 62, 43, 156, 141, 177, 106, 246,
    72,
  ])
);
export const ZOV = ZOV_KEYPAIR.publicKey;

export const ADMIN_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    126, 107, 150, 33, 182, 94, 110, 60, 114, 206, 254, 24, 239, 162, 234, 67,
    205, 140, 165, 139, 247, 237, 172, 42, 19, 8, 4, 165, 159, 87, 234, 217,
    161, 178, 195, 93, 195, 139, 69, 187, 37, 17, 38, 231, 182, 3, 104, 21,
    176, 177, 142, 170, 1, 91, 82, 233, 74, 27, 72, 166, 107, 90, 62, 61,
  ])
);
export const ADMIN = ADMIN_KEYPAIR.publicKey;

export const MANAGER_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    226, 130, 225, 136, 148, 25, 22, 223, 210, 237, 204, 119, 76, 221, 105,
    139, 85, 131, 182, 63, 47, 53, 28, 194, 60, 0, 193, 217, 121, 157, 242,
    38, 170, 242, 36, 191, 62, 122, 27, 144, 191, 183, 129, 116, 28, 210, 131,
    191, 89, 60, 70, 35, 21, 211, 106, 95, 186, 141, 102, 172, 212, 212, 106,
    173,
  ])
);
export const MANAGER = MANAGER_KEYPAIR.publicKey;

export const INITIAL_MANAGER_KEYPAIR = Keypair.fromSecretKey(
  new Uint8Array([
    213, 7, 223, 173, 216, 125, 138, 102, 221, 201, 237, 125, 174, 27, 139,
    53, 106, 114, 233, 61, 137, 247, 67, 247, 164, 132, 132, 1, 15, 187, 21,
    60, 116, 100, 219, 214, 248, 252, 130, 149, 99, 118, 195, 63, 137, 2, 0,
    128, 147, 91, 123, 126, 132, 235, 228, 48, 120, 86, 144, 109, 1, 146, 24,
    75,
  ])
);
export const INITIAL_MANAGER = INITIAL_MANAGER_KEYPAIR.publicKey;