[features]
seeds = false
skip-lint = false

[programs.localnet]
zynk_protocol = "7UAhcDLNRpKa4HuCk5MkCLxRGLeRnbjqGxhjePdxPcqB"

[programs.devnet]
zynk_protocol = "AHPfQdfzNVS7vLA8Lqqo75XaVGwDjQBobqwvDqBZ5njX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[test.validator]
rpc_port = 8899
confirm_timeout_ms = 10000

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
